apiVersion: v1
kind: Service
metadata:
  labels:
    app: patientapi # the service app name
  name: patientapi-service # name for the service deployment
spec:
  ports:
    - port: 8080 # the port used to call service from external apps
      targetPort: 80 # the container port
  selector:
    app: patientapi-pod # the POD where the image will be deployed in container
  type: LoadBalancer # provides a public access to the service        